// Decompiled with JetBrains decompiler
// Type: Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfoFlags
// Assembly: Microsoft.CSharp, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// MVID: DC6D2496-69CF-48FE-AD2F-4EB0C173A6F4
// Assembly location: C:\Users\Admin\Desktop\RE\ChickWinx64\Microsoft.CSharp.dll
// XML documentation location: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\Microsoft.CSharp.xml

using System;
using System.ComponentModel;

#nullable disable
namespace Microsoft.CSharp.RuntimeBinder
{
  /// <summary>Represents information about C# dynamic operations that are specific to particular arguments at a call site. Instances of this class are generated by the C# compiler.</summary>
  [Flags]
  [EditorBrowsable(EditorBrowsableState.Never)]
  public enum CSharpArgumentInfoFlags
  {
    /// <summary>No additional information to represent.</summary>
    None = 0,
    /// <summary>The argument's compile-time type should be considered during binding.</summary>
    UseCompileTimeType = 1,
    /// <summary>The argument is a constant.</summary>
    Constant = 2,
    /// <summary>The argument is a named argument.</summary>
    NamedArgument = 4,
    /// <summary>The argument is passed to a ref parameter.</summary>
    IsRef = 8,
    /// <summary>The argument is passed to an out parameter.</summary>
    IsOut = 16, // 0x00000010
    /// <summary>The argument is a <see cref="T:System.Type" /> indicating an actual type name used in source. Used only for target objects in static calls.</summary>
    IsStaticType = 32, // 0x00000020
  }
}
